---
title: '`r params$subclass` results'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    css: assets/css/dashboard.css

params:
  subclass: ''
  filedate: ''
  seurat_dir: ''
  templates_dir: ''
  ensembl_genes: ''
  nameset: ''
  geno: ''
  drug: ''
  analyses: !r c('Tg-VvsWt-V', 'Tg-DvsWt-V', 'Tg-DvsTg-V')
  fdr_cutoff: 0.99
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F, dpi = 300)

library(knitr)
library(kableExtra)
library(DT)
library(plotly)
library(gprofiler2)
library(viridis)
library(Cairo)

options(bitmapType = 'cairo')


subclass <- params$subclass
filedate <- params$filedate
seurat_dir <- params$seurat_dir
ensembl_genes <- params$ensembl_genes
nameset <- params$nameset
geno <- params$geno
drug <- params$drug
analyses <- params$analyses
fdr_cutoff <- params$fdr_cutoff
```

```{r data, include = F}
names(analyses) <- c('geno', 'geno_drug', 'drug')

# Obtain clusters
file_regex <- str_c(filedate, '\\.', nameset, '\\.RNA.+\\.csv\\.gz')
file_matches <- list.files(file.path(seurat_dir, nameset), pattern = file_regex)

# clusters <- unique(str_match(file_matches, file_regex)[,2])
# clusters <- append(clusters[clusters != subclass], subclass, after = 0)  # order subclass before clusters
clusters = nameset ###### workaround
names(clusters) <- clusters


# Read in data
genes_files <- lapply(clusters, function(c) lapply(analyses, function(a) {
  fread(file.path(seurat_dir, nameset, str_c(filedate, c, 'RNA', a, 'csv.gz', sep = '.')))
}))

# Merge data
results <- lapply(clusters, function(c) {
  
  colnames <- c('Gene_id', 'log2FoldChange', 'padj', 'pvalue')
  result <- genes_files[[c]][[1]][, ..colnames]

  for (i in head(seq(genes_files[[c]]), -1)) {
    gene_file <- genes_files[[c]][[i + 1]][, ..colnames]
    result <- merge(result, gene_file, by = 'Gene_id', all = T, suffixes = c('', str_c('.', names(analyses)[[i + 1]])))
  }
  
  ########### unexpected, input files had NA for some Gene_ids.
  result <- result[!is.na(Gene_id)]
  setnames(result, colnames[-1], str_c(colnames[-1], '.', names(analyses)[[1]]), 
           skip_absent = TRUE)

  result <- merge(ensembl_genes, result, by.x = 'ensembl_gene_id', by.y = 'Gene_id')
  
  # Add gene category
  result[, category := fcase(
  	(log2FoldChange.geno > 0 & padj.geno < fdr_cutoff) & ((log2FoldChange.geno_drug < 0 & padj.geno_drug < fdr_cutoff) | (log2FoldChange.drug < 0 & padj.drug < fdr_cutoff)), 'suppression',
  	(log2FoldChange.geno > 0 & padj.geno < fdr_cutoff) & (log2FoldChange.drug > 0 & padj.drug < fdr_cutoff), 'compensatory enhancement',
  	(log2FoldChange.geno < 0 & padj.geno < fdr_cutoff) & ((log2FoldChange.geno_drug > 0 & padj.geno_drug < fdr_cutoff) | (log2FoldChange.drug > 0 & padj.drug < fdr_cutoff)), 'enhancement',
  	(log2FoldChange.geno < 0 & padj.geno < fdr_cutoff) & (log2FoldChange.drug < 0 & padj.drug < fdr_cutoff), 'compensatory suppression',
  	default = NA_character_
  )]
  
  # Add gene direction
  result[, direct := fcase(
    category == 'suppression' & (log2FoldChange.drug < 0 & padj.drug < fdr_cutoff), T,
    category == 'enhancement' & (log2FoldChange.drug > 0 & padj.drug < fdr_cutoff), T,
    category %in% c('suppression', 'enhancement'), F,
    default = NA
  )]
  
  # Rearrange columns
  var_names <- c('ensembl_gene_id', 'external_gene_name', 'gene_biotype', 'chromosome_name', 'category', 'direct')
  setcolorder(
    result, 
    c(
      var_names,
      setdiff(names(result), c(var_names, names(modules))),
      names(modules)
    )
  )
})
```

```{r pages, include = F}
# Generate cell type/subclass pages
pages <- NULL

for (r in names(results)) {
  pages <- c(pages, knit_expand(file = file.path(templates_dir, 'bulk_page.Rmd')))
}
```

`r paste(knit(text = pages), collapse = '\n')`
