---
title: '`r ifelse(params$typeout == '', params$nameset, params$typeout)` results'
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    css: assets/css/dashboard.css

params:
  base_dir: ''
  templates_dir: 'templates'
  ensembl_genes: ''
  nameset: ''
  geno: ''
  drug: ''
  filedate: ''
  typeout: ''
  analyses: !r c('Tg-VvsWt-V', 'Tg-DvsWt-V', 'Tg-DvsTg-V')
  de_cols: !r c('GENE', 'avg_log2FC', 'p_val_adj', 'pct.1', 'pct.2')
  de_names: !r c('Log2FC', 'Pval (adj)', 'Pct 1', 'Pct 2')
  pval_col: 'p_val'
  lfc_unshrunken_col: 'avg_log2FC'
  fdr_cutoff: 0.05
  lfc_cutoff_geno: 0.55 
  lfc_cutoff_drug: 0.5
---

```{r setup, echo = F}
knitr::opts_chunk$set(echo = F, message = F, warning = F, dpi = 300)

library(knitr)
library(kableExtra)
library(DT)
library(plotly)
library(gprofiler2)
library(viridis)
library(Cairo)

options(bitmapType = 'cairo')


base_dir <- params$base_dir
templates_dir <- params$templates_dir
ensembl_genes <- params$ensembl_genes
nameset <- params$nameset
geno <- params$geno
drug <- params$drug
filedate <- params$filedate
typeout <- params$typeout
analyses <- params$analyses
de_cols <- params$de_cols
de_names <- params$de_names
pval_col <- params$pval_col
lfc_unshrunken_col <- params$lfc_unshrunken_col
fdr_cutoff <- params$fdr_cutoff
lfc_cutoff_geno <- params$lfc_cutoff_geno
lfc_cutoff_drug <- params$lfc_cutoff_drug

is_sc <- typeout != ''
if (!is_sc) typeout = nameset

include_wt <- ifelse(length(analyses) == 4, T, F)

gene_col <- de_cols[[1]]
lfc_col <- de_cols[[2]]
p_col <- de_cols[[3]]

ensembl_var <- ifelse(is_sc, 'external_gene_name', 'ensembl_gene_id')
```

```{r data, include = F}
modules <- c('TREAT-AD.Mouse.Genes.txt', 'TMT-LP.Mouse.Genes.txt', 'Mostafavi_etal.Mouse.Genes.txt', 'Milind_etal.Mouse.Genes.txt', 'AD_modules_full.tsv')
names(modules) <- c('treatAD', 'tmtAD', 'mostafavi', 'milind', 'wan')

var_names <- c('geno', 'geno_drug', 'drug')

if (include_wt) {
  var_names <- c(var_names, 'drug_wt')
}

names(analyses) <- var_names

lfc_geno <- str_c(lfc_col, 'geno', sep = '.')
lfc_drug <- str_c(lfc_col, 'drug', sep = '.')
lfc_geno_drug <- str_c(lfc_col, 'geno_drug', sep = '.')
p_geno <- str_c(p_col, 'geno', sep = '.')
p_drug <- str_c(p_col, 'drug', sep = '.')
p_geno_drug <- str_c(p_col, 'geno_drug', sep = '.')


# Obtain clusters
if (is_sc) {
  file_regex <- str_c(filedate, '\\.', nameset, '\\.(.+)\\.RNA.+\\.csv\\.gz')
  file_matches <- list.files(file.path(base_dir, typeout), pattern = file_regex)
  clusters <- unique(str_match(file_matches, file_regex)[,2])
  clusters <- append(clusters[clusters != typeout], typeout, after = 0)  # order subclass before clusters
} else {
  clusters <- nameset
}

names(clusters) <- clusters

# Read in data
genes_files <- lapply(clusters, function(c) lapply(analyses, function(a) {
  fn <- ifelse(is_sc, str_c(nameset, '.', c), nameset)
  
  fread(file.path(base_dir, typeout, str_c(filedate, fn, 'RNA', a, 'csv.gz', sep = '.')))
}))

# Merge data
results <- lapply(clusters, function(c) {
  
  result <- genes_files[[c]][[1]][!(is.na(get(gene_col))), ..de_cols]

  for (i in head(seq(genes_files[[c]]), -1)) {
    gene_file <- genes_files[[c]][[i + 1]][, ..de_cols]
    result <- merge(result, gene_file, by = gene_col, all = T, suffixes = c('', str_c('.', names(analyses)[[i + 1]])))
  }
  
  result <- merge(ensembl_genes, result, by.x = ensembl_var, by.y = gene_col)
  setnames(result, de_cols, str_c(de_cols, '.', names(analyses)[[1]]), skip_absent = T)
  
  # Add gene category
  result[, category := fcase(
  	(get(lfc_geno) > 0 & get(p_geno) < fdr_cutoff) & ((get(lfc_geno_drug) < 0 & get(p_geno_drug) < fdr_cutoff) | (get(lfc_drug) < 0 & get(p_drug) < fdr_cutoff)), 'suppression',
  	(get(lfc_geno) > 0 & get(p_geno) < fdr_cutoff) & (get(lfc_drug) > 0 & get(p_drug) < fdr_cutoff), 'compensatory enhancement',
  	(get(lfc_geno) < 0 & get(p_geno) < fdr_cutoff) & ((get(lfc_geno_drug) > 0 & get(p_geno_drug) < fdr_cutoff) | (get(lfc_drug) > 0 & get(p_drug) < fdr_cutoff)), 'enhancement',
  	(get(lfc_geno) < 0 & get(p_geno) < fdr_cutoff) & (get(lfc_drug) < 0 & get(p_drug) < fdr_cutoff), 'compensatory suppression',
  	default = NA_character_
  )]
  
  # Add gene direction
  result[, direct := fcase(
    category == 'suppression' & (get(lfc_drug) < 0 & get(p_drug) < fdr_cutoff), T,
    category == 'enhancement' & (get(lfc_drug) > 0 & get(p_drug) < fdr_cutoff), T,
    category %in% c('suppression', 'enhancement'), F,
    default = NA
  )]
  
  # Rearrange columns
  var_names <- c('ensembl_gene_id', 'external_gene_name', 'gene_biotype', 'chromosome_name', 'category', 'direct')
  tf_names <- c('Family', 'is_mouse_chembl', 'chembl_protein_labels')
  setcolorder(
    result, 
    c(
      var_names,
      setdiff(names(result), c(var_names, names(modules), tf_names)),
      names(modules),
      tf_names
    )
  )
})
```

```{r pages, include = F}
# Generate cell type/subclass pages
pages <- NULL

for (r in names(results)) {
  pages <- c(pages, knit_expand(file = file.path(templates_dir, 'page.Rmd')))
}
```

`r paste(knit(text = pages), collapse = '\n')`
